### ISSUE TITLE
Balloons go up! circumvented

### ISSUE THREAD

**Issue by torso** [the-butterfly-effect/tbe#303] opened 2016-06-30 11:41 UTC
Placing the floor below left of the left volley ball will make it start rolling.

**Comment by Wuzzy2** [comment] 2016-06-30 16:12
Not actually an issue of the level itself, but with the way the game allows to place objects.
IMO objects should not be allowed to be placed in a way that kinda push other objects since they end of slightly “inside” them.

As such, this is an duplicate of #131.

**Closed by Wuzzy2** 2016-06-30 16:12 UTC
Labels: bug, duplicate

**Comment by torso** [comment] 2016-06-30 16:16
Didn't look like it penetrated the ball. It was more about taking advantage of the ball falling slightly.

This technique also works in Float, balloon, float!

**Comment by lspacenl** [comment] 2016-07-05 09:30
If that's true then the ball was not placed correctly, unless its intended and I don't believe that.
