### ISSUE TITLE
Figure out MacOSX builds

### ISSUE THREAD

**Issue by kaa-ching** [the-butterfly-effect/tbe#45] opened 2015-10-20 21:47 UTC
Will sit together with a Mac expert on Oct 27th. If possible, we'll build a MacOSX package.

**Comment by kaa-ching** [comment] 2015-10-27 23:21
The following commits help towards this goal:
e709cfa378b4b825abd93a3dbb0912e760f9174d
159af0394a40da03c1933c3b6844beaf9996430c
9dd71d2bdf01d185118c17e2d0fee39608aa37e0
a1ca0b27c3d8956c57b1e82c7f82af762e97fd27
6fbec98da0bf05c2293a18fe5ba6bb6382ea526d

**Comment by kaa-ching** [comment] 2015-10-27 23:23
Still to do:
 * [ ] setup packaging
 * [ ] complete documentation
 * [ ] fix level "Extreme Tux Racer", that doesn't work on Aschwin's laptop.
 * [ ] figure out what's happening with the keyboard focus on Mac at startup
 * [ ] complete the *full* regression in one go

**Comment by amarsman** [comment] 2015-10-27 23:35
Build on Mac OS X Yosemite 10.10.5 (14F1021) using Command Line Tools (OS X 10.10) for Xcode 7.1.0.

Installed: http://download.qt.io/official_releases/qt/4.8/4.8.7/qt-opensource-mac-4.8.7.dmg

`make clean`
`make`
`./tbe`

and enjoy the game!

**Comment by amarsman** [comment] 2015-12-12 14:58
When using CMake in QtCreator make sure to use the CMake arguments otherwise you will get build failures:

-DCMAKE_BUILD_TYPE=Debug -DWITH_DOCS=on -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

**Comment by kaa-ching** [comment] 2015-12-13 19:24
issue #57 was also related to this issue.

**Comment by amarsman** [comment] 2015-12-27 06:21
Currently TBE can't be build on Mac OS X 10.11 (El Capitan). As upgrading to the latest version is done Quickly in the Mac eco system this is a big problem, see the wiki page on Mac OS X for more information: https://github.com/kaa-ching/tbe/wiki/MacOSXBuild

**Comment by kaa-ching** [comment] 2015-12-28 07:57
Because I forgot a space in the commit message:

[master fa2ead1] issue#45: use CMake's automoc instead of running moc on all header files

This should make @amarsman slightly happier :wink:

**Comment by amarsman** [comment] 2016-01-19 23:10
Just did a pull request, in my branch MacOSXBuild the directory layout is updated so TBE can be started again and looks more like a regular Mac OS X application. Also clicking on tbe.app in the Mac OS X Finder works so the layout I created is sufficient for that.

Next steps for Mac OS X when the branch MacOSXBuild is integrated:
1) update the Mac OS X build wiki page so the instructions are correct for others to reproduce
2) create a .dmg file that also includes the Qt5 libs and needed support files so it can be distributed to other Mac OS X users for testing
3) create an application icon in the Mac format
4) Improve the generated .dmg file to include a link to the Applications folder and a nice background image
5) verify that level "Extreme Tux Racer" still doesn't work and fix if needed.
6) Mac OS X has a different application focus behaviour depending if you start from within the Finder or on the command line. Add an option that also on the command line the application gets focus so the regression tests can be started.
7) Regression test should run in one go.

When step two is finished the generated .dmg file can be released for alpha testing by a couple of people.

Would be nice to go to Brussels for FOSDEM and have at least the first 4 steps above ready or use that weekend to complete the 4 steps..

**Comment by kaa-ching** [comment] 2016-01-20 08:20
I just adjusted your comment to have checkboxes - that way you can check your progress :wink:

**Comment by amarsman** [comment] 2016-01-27 16:10
Currently it doesn't build because of the addition of gettext, a new dependency that I don't like myself. I'm working on some cmake magic to make it work again. Thanks for the icons @kaa-ching, when I have a working version again I will integrate that.

**Comment by kaa-ching** [comment] 2016-01-31 23:08
@marsman: i remember the icon needs work. Can you please re-iterate what exactly?

**Comment by amarsman** [comment] 2016-01-31 23:24
During FOSDEM @kaa-ching and I made the Mac OS X version build again. We also added the application icon. When the icon is large it looks fine, when it's small the text TBE disturbs the image, it doesn't look like a butterfly anymore for me:
for smaller icons only show the butterfly, for larger icons it's fine to show TBE also.

**Comment by amarsman** [comment] 2016-01-31 23:28
Current status:
* [x] fix the build after the introduction of gettext.
* [x] create an application icon in the Mac format
* [x] use the application icon
* [ ] update the Mac OS X build wiki page so the instructions are correct for others to reproduce
* [ ] refactor cmake files
* [ ] create a .dmg file that also includes the Qt5 libs and needed support files so it can be distributed to other Mac OS X users for testing
* [ ] Improve the generated .dmg file to include a link to the Applications folder and a nice background image
* [ ] verify that level "Extreme Tux Racer" still doesn't work and fix if needed.
* [ ] Mac OS X has a different application focus behaviour depending if you start from within the Finder or on the command line. Add an option that also on the command line the application gets focus so the regression tests can be started.
* [ ] Regression test should run in one go.

**Comment by amarsman** [comment] 2016-02-12 04:16
Build on Mac OS X works again since almost 2 weeks:

commit 7154fa48992645330417d6ad9b5ceab9def0018b
Author: Aschwin Marsman <a.marsman@aynik.com>
Date:   Sun Jan 31 14:26:17 2016 +0100

    @kaaching added a new dependency that broke the MacOSX build. Fixed but needs some refactoring. TBE can be started again.

**Comment by amarsman** [comment] 2016-02-12 04:45
Updated the Mac OS X build wiki page so the instructions are correct for others to reproduce: 
https://github.com/kaa-ching/tbe/wiki/MacOSXBuild

**Comment by amarsman** [comment] 2016-03-09 20:15
Updated the checklist above together with @kaa-ching

**Comment by amarsman** [comment] 2016-03-09 20:40
The application icon is now installed, when the application is run the correct icon is shown.

**Comment by amarsman** [comment] 2016-04-24 12:47
Current status: application can be build, used libraries/frameworks copied inside the application structure so it's easy to distribute to others. Application is build on OS X El Capitan and can be used on the same OS X version. 

Currently the following libraries/frameworks are installed with their size: 
5.8M	QtCore.framework
520K	QtDBus.framework
5.8M	QtGui.framework
352K	QtPrintSupport.framework
356K	QtSvg.framework
6.3M	QtWidgets.framework
288K	QtXml.framework
992K	libiconv.2.dylib
 52K		libintl.8.dylib

Looks like we should be able to trim the list but the candidates are small in size.

I suspect that the self build libraries libiconv.2.dylib and/or libintl.8.dylib are causing the fact that the application can't be used on older OS X versions.

**Comment by amarsman** [comment] 2016-04-24 12:50
Current status:
* [x] fix the build after the introduction of gettext.
* [x] create an application icon in the Mac format
* [x] use the application icon
* [x] update the Mac OS X build wiki page so the instructions are correct for others to reproduce
* [x] install adapted plist file
* [x] create a tbe.app that also includes the Qt5 libs and needed support files so it can be distributed to other Mac OS X users for testing

Optional:
* [ ] create a .dmg file that also includes the Qt5 libs and needed support files so it can be distributed to other Mac OS X users for testing
* [ ] refactor cmake files
* [ ] improve the generated .dmg file to include a link to the Applications folder and a nice background image
* [ ] Mac OS X has a different application focus behaviour depending if you start from within the Finder or on the command line. Add an option that also on the command line the application gets focus so the regression tests can be started.
* [ ] regression test should run in one go.
* [ ] generate and put plist in the location

**Comment by amarsman** [comment] 2016-04-24 12:52
OS X version can be distributed to other users so this ticket doesn't block a milestone B release anymore. Should we close this issue and create a new one with the optional tasks @kaa-ching? Or do we keep this one open?

**Comment by kaa-ching** [comment] 2016-05-01 12:01
I agree: fork issue, close this one.

**Comment by amarsman** [comment] 2016-05-13 00:58
Created a new ticket for the next milestone: [Improve OS X support](https://github.com/the-butterfly-effect/tbe/issues/226).

**Closed by amarsman** 2016-05-13 00:58 UTC
Labels: enhancement, packaging
