### ISSUE TITLE
TBE is unable to start level with pingu in toolbox

### ISSUE THREAD

**Issue by Wuzzy2** [the-butterfly-effect/tbe#209] opened 2016-04-23 00:46 UTC
If I attempt to start a level with a pingu in the toolbox, I get a crash and this in console:

```ASSERT: "anImageBaseName.isEmpty() == false" in file /home/wuzzy/src/tbe/tbe/src/view/ImageCache.cpp, line 46```

To test this, just take any level with a pingu, open it in text editor and move the object into `<toolbox>`, then try to load it in TBE.
Example:
```
<toolboxitem count="1">
<object type="PingusWalkLeft"/>
</toolboxitem>
```

Revision: fa4289fee2ee5f4c159a0d2b46e794282800fa4c

**Comment by kaa-ching** [comment] 2016-04-23 10:11
Will have to be addressed when I also address the left/right starting. I don't intend to do that for milestone B anymore.

**Comment by kaa-ching** [comment] 2016-05-28 12:33
OK, I'm almost done fixing this.
You'll need to supply pingus to the toolbox like this:
```
        <toolboxitem count="1" name="Pingus Left">
            <object type="PingusWalkLeft" />
        </toolboxitem>
        <toolboxitem count="1" name="Pingus Right">
            <object type="PingusWalkRight" />
        </toolboxitem>
        <toolboxitem count="1" name="Sleeping Pingus">
            <object type="PingusSleeping" />
        </toolboxitem>
```
It's important that the name is unique, no clue why.

**Comment by kaa-ching** [comment] 2016-05-29 10:27
Regression may work, but the level creator is now slightly broken, see screenshot.
Reopening.
![pingus size wrong](https://cloud.githubusercontent.com/assets/4249656/15632606/bcd87428-2598-11e6-9dc9-b15673dfd4e3.png)

**Comment by kaa-ching** [comment] 2016-05-29 10:53
Committed an ugly hack. at least the box is smaller now. As this has to do with the menu, I'm not going to really fix it - this code is due to be removed anyway.

**Closed** 2016-05-29 13:04 UTC
Labels: bug
