### ISSUE TITLE
Various aborts & segfaults in level creator

### ISSUE THREAD

**Issue by glixx** [the-butterfly-effect/tbe#6] opened 2015-08-09 20:58 UTC
* [x] File->Switch to level editor->File->Open level->Go!

   `Program received signal SIGSEGV, Segmentation fault.`
   `0xb7093fba in __dynamic_cast () from /lib/libstdc++.so.6`
* [x] Object::connect: No such slot ResizingGraphicsView::on_objectEditor_destroyed() 
* [x] Object::disconnect: No such signal ViewWorld::levelWon() in /home/klaas/Programming/tbe-github/src/view/resizinggraphicsview.cpp:79
* [x] deleting an object that is already existing when level is loaded in the level editor, causes a segfault. deletion of objects from the toolbox in normal game operation works.
* [x] deleting an 'empty' line in the goal editor crashes TBE.

(edited by Kaa-ching to contain more found crashes and warnings)

**Comment by kaa-ching** [comment] 2015-08-10 11:40
While planning to disable the level editor in the milestone A release, this will be fixed because Pareon Verify will pick up on this.

**Comment by kaa-ching** [comment] 2015-09-06 08:48
No longer in the menu, moving to milestone B.

**Comment by kaa-ching** [comment] 2015-11-27 08:30
Pareon Verify:
```
===== PAREON VERIFY =====
[M0224] Segmentation-violation signal delivered to unanalyzed function `QObject::disconnect(QObject const*, char const*, QObject const*, char const*)' called in
    function ResizingGraphicsView::clearViewWorld() at tbe-github/src/view/resizinggraphicsview.cpp:79
    called from function MainWindow::purgeLevel() at tbe-github/src/view/MainWindow.cpp:382
    called from function MainWindow::loadLevel(QString const&) at tbe-github/src/view/MainWindow.cpp:84
    called from function MainWindow::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) at tbe-github/build/src/view/moc_MainWindow.cxx:174
    called from unanalyzed function QMetaObject::activate(QObject*, QMetaObject const*, int, void**)
    called from function ChooseLevel::loadLevel(QString const&) at tbe-github/build/src/view/moc_ChooseLevel.cxx:108
    called from function ChooseLevel::on_pushButton_go_clicked() at tbe-github/src/view/ChooseLevel.cpp:126
    called from function ChooseLevel::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) at tbe-github/build/src/view/moc_ChooseLevel.cxx:58
    called from function ChooseLevel::qt_metacall(QMetaObject::Call, int, void**) at tbe-github/build/src/view/moc_ChooseLevel.cxx:98
    called from unanalyzed function QApplication::exec()
    called from function main at tbe-github/src/main.cpp:315
    ^^^ application start ^^^
```

**Comment by kaa-ching** [comment] 2015-11-27 08:37
_File->Switch to level editor->File->Open level->Go!_

Requires me to click _Go!_ twice, at the second time, tbe aborts:

```
ASSERT failure in QList<T>::operator[]: "index out of range", file /usr/include/qt4/QtCore/qlist.h, line 477
WARNING: Process 23695 caught terminating signal 6 (Aborted).
Aborted (core dumped)
```

**Comment by kaa-ching** [comment] 2015-11-27 08:41
Relevant part from the backtrace in the core dump:
```
#4  0x00007fc45548c804 in qFatal(char const*, ...) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#5  0x00000000004feaa3 in QList<QGraphicsView*>::operator[] (this=0x7ffe2a8993c0, i=0)
    at /usr/include/qt4/QtCore/qlist.h:477
#6  0x00000000004fd773 in ViewObject::~ViewObject (this=0x21a9290, __in_chrg=<optimized out>)
    at /home/klaas/Programming/tbe-github/src/view/ViewObject.cpp:86
#7  0x00000000004fd866 in ViewObject::~ViewObject (this=0x21a9290, __in_chrg=<optimized out>)
    at /home/klaas/Programming/tbe-github/src/view/ViewObject.cpp:90
#8  0x00007fc4562dc2c6 in QGraphicsScene::clear() () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#9  0x00007fc4562dc325 in QGraphicsScene::~QGraphicsScene() () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#10 0x0000000000502100 in ViewWorld::~ViewWorld (this=0x1dfee90, __in_chrg=<optimized out>)
    at /home/klaas/Programming/tbe-github/src/view/ViewWorld.cpp:54
#11 0x0000000000502138 in ViewWorld::~ViewWorld (this=0x1dfee90, __in_chrg=<optimized out>)
    at /home/klaas/Programming/tbe-github/src/view/ViewWorld.cpp:57
#12 0x00000000004f50d8 in ResizingGraphicsView::clearViewWorld (this=0x1cfd900)
    at /home/klaas/Programming/tbe-github/src/view/resizinggraphicsview.cpp:76
```

**Comment by kaa-ching** [comment] 2016-01-25 22:14
The missing slot will be fixed when I overhaul the ObjectEditor as part of issue #66.

I'm too tired to fix the last crash now.

**Comment by Wuzzy2** [comment] 2016-02-06 20:45
When you try to click remove a goal in the goal/fail editor while there is at least one goal, but nothing is selected, TBE crashes.
If you do the same with fails instead of goals, the same happens.

How to reproduce:
* Start level editor
* Create new level
* Open goal/fail editor
* Add goal (“+” button)
* Do *not* click or select anything!
* Remove goal (“-” button)

Revision: 678985f06f63c7003aa5a03e086332f0cd13b3c1

**Comment by kaa-ching** [comment] 2016-02-20 23:07
done :smile:

**Closed by kaa-ching** 2016-02-20 23:07 UTC
Labels: bug
